// Generated by view binder compiler. Do not edit!
package com.ericaskari.healthapplication;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainCardItemBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final CoordinatorLayout homeCard;

  @NonNull
  public final ImageView homeCardImage;

  @NonNull
  public final TextView homeCardText;

  private ActivityMainCardItemBinding(@NonNull CoordinatorLayout rootView,
      @NonNull CoordinatorLayout homeCard, @NonNull ImageView homeCardImage,
      @NonNull TextView homeCardText) {
    this.rootView = rootView;
    this.homeCard = homeCard;
    this.homeCardImage = homeCardImage;
    this.homeCardText = homeCardText;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainCardItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainCardItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main_card_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainCardItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      CoordinatorLayout homeCard = (CoordinatorLayout) rootView;

      id = R.id.home_card_image;
      ImageView homeCardImage = ViewBindings.findChildViewById(rootView, id);
      if (homeCardImage == null) {
        break missingId;
      }

      id = R.id.home_card_text;
      TextView homeCardText = ViewBindings.findChildViewById(rootView, id);
      if (homeCardText == null) {
        break missingId;
      }

      return new ActivityMainCardItemBinding((CoordinatorLayout) rootView, homeCard, homeCardImage,
          homeCardText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
