// Generated by view binder compiler. Do not edit!
package com.ericaskari.healthapplication;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.SeekBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

/**
 * Generated by view binder compiler.
 */
public final class NewPainLogAltlayoutBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final Button buttonLogPainReady;

  @NonNull
  public final ConstraintLayout constraintLayout;

  @NonNull
  public final EditText editTextDescription;

  @NonNull
  public final EditText editTextMedicineTaken;

  @NonNull
  public final RadioButton radioButtonPainLogNo;

  @NonNull
  public final RadioButton radioButtonPainLogYes;

  @NonNull
  public final RadioGroup radioGroupLogPain;

  @NonNull
  public final SeekBar seekBarHowStrongIsThePain;

  @NonNull
  public final TextView textView4;

  @NonNull
  public final TextView textView6;

  @NonNull
  public final TextView textViewPainStrenght;

  private NewPainLogAltlayoutBinding(@NonNull CoordinatorLayout rootView,
      @NonNull Button buttonLogPainReady, @NonNull ConstraintLayout constraintLayout,
      @NonNull EditText editTextDescription, @NonNull EditText editTextMedicineTaken,
      @NonNull RadioButton radioButtonPainLogNo, @NonNull RadioButton radioButtonPainLogYes,
      @NonNull RadioGroup radioGroupLogPain, @NonNull SeekBar seekBarHowStrongIsThePain,
      @NonNull TextView textView4, @NonNull TextView textView6,
      @NonNull TextView textViewPainStrenght) {
    this.rootView = rootView;
    this.buttonLogPainReady = buttonLogPainReady;
    this.constraintLayout = constraintLayout;
    this.editTextDescription = editTextDescription;
    this.editTextMedicineTaken = editTextMedicineTaken;
    this.radioButtonPainLogNo = radioButtonPainLogNo;
    this.radioButtonPainLogYes = radioButtonPainLogYes;
    this.radioGroupLogPain = radioGroupLogPain;
    this.seekBarHowStrongIsThePain = seekBarHowStrongIsThePain;
    this.textView4 = textView4;
    this.textView6 = textView6;
    this.textViewPainStrenght = textViewPainStrenght;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static NewPainLogAltlayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static NewPainLogAltlayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.new_pain_log_altlayout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static NewPainLogAltlayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonLogPainReady;
      Button buttonLogPainReady = ViewBindings.findChildViewById(rootView, id);
      if (buttonLogPainReady == null) {
        break missingId;
      }

      id = R.id.constraintLayout;
      ConstraintLayout constraintLayout = ViewBindings.findChildViewById(rootView, id);
      if (constraintLayout == null) {
        break missingId;
      }

      id = R.id.editTextDescription;
      EditText editTextDescription = ViewBindings.findChildViewById(rootView, id);
      if (editTextDescription == null) {
        break missingId;
      }

      id = R.id.editTextMedicineTaken;
      EditText editTextMedicineTaken = ViewBindings.findChildViewById(rootView, id);
      if (editTextMedicineTaken == null) {
        break missingId;
      }

      id = R.id.radioButtonPainLogNo;
      RadioButton radioButtonPainLogNo = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonPainLogNo == null) {
        break missingId;
      }

      id = R.id.radioButtonPainLogYes;
      RadioButton radioButtonPainLogYes = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonPainLogYes == null) {
        break missingId;
      }

      id = R.id.radioGroupLogPain;
      RadioGroup radioGroupLogPain = ViewBindings.findChildViewById(rootView, id);
      if (radioGroupLogPain == null) {
        break missingId;
      }

      id = R.id.seekBarHowStrongIsThePain;
      SeekBar seekBarHowStrongIsThePain = ViewBindings.findChildViewById(rootView, id);
      if (seekBarHowStrongIsThePain == null) {
        break missingId;
      }

      id = R.id.textView4;
      TextView textView4 = ViewBindings.findChildViewById(rootView, id);
      if (textView4 == null) {
        break missingId;
      }

      id = R.id.textView6;
      TextView textView6 = ViewBindings.findChildViewById(rootView, id);
      if (textView6 == null) {
        break missingId;
      }

      id = R.id.textViewPainStrenght;
      TextView textViewPainStrenght = ViewBindings.findChildViewById(rootView, id);
      if (textViewPainStrenght == null) {
        break missingId;
      }

      return new NewPainLogAltlayoutBinding((CoordinatorLayout) rootView, buttonLogPainReady,
          constraintLayout, editTextDescription, editTextMedicineTaken, radioButtonPainLogNo,
          radioButtonPainLogYes, radioGroupLogPain, seekBarHowStrongIsThePain, textView4, textView6,
          textViewPainStrenght);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
