// Generated by view binder compiler. Do not edit!
package com.ericaskari.healthapplication;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class NewPainLogBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final Button buttonLogPainReady;

  @NonNull
  public final ConstraintLayout constraintLayout;

  @NonNull
  public final EditText editTextDescription;

  @NonNull
  public final TextView pickAPain;

  @NonNull
  public final SeekBar seekBarHowStrongIsThePain;

  @NonNull
  public final Spinner selectPainSpinner;

  @NonNull
  public final TextView textView6;

  @NonNull
  public final TextView textViewPainStrenght;

  private NewPainLogBinding(@NonNull CoordinatorLayout rootView, @NonNull Button buttonLogPainReady,
      @NonNull ConstraintLayout constraintLayout, @NonNull EditText editTextDescription,
      @NonNull TextView pickAPain, @NonNull SeekBar seekBarHowStrongIsThePain,
      @NonNull Spinner selectPainSpinner, @NonNull TextView textView6,
      @NonNull TextView textViewPainStrenght) {
    this.rootView = rootView;
    this.buttonLogPainReady = buttonLogPainReady;
    this.constraintLayout = constraintLayout;
    this.editTextDescription = editTextDescription;
    this.pickAPain = pickAPain;
    this.seekBarHowStrongIsThePain = seekBarHowStrongIsThePain;
    this.selectPainSpinner = selectPainSpinner;
    this.textView6 = textView6;
    this.textViewPainStrenght = textViewPainStrenght;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static NewPainLogBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static NewPainLogBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.new_pain_log, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static NewPainLogBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonLogPainReady;
      Button buttonLogPainReady = ViewBindings.findChildViewById(rootView, id);
      if (buttonLogPainReady == null) {
        break missingId;
      }

      id = R.id.constraintLayout;
      ConstraintLayout constraintLayout = ViewBindings.findChildViewById(rootView, id);
      if (constraintLayout == null) {
        break missingId;
      }

      id = R.id.editTextDescription;
      EditText editTextDescription = ViewBindings.findChildViewById(rootView, id);
      if (editTextDescription == null) {
        break missingId;
      }

      id = R.id.pickAPain;
      TextView pickAPain = ViewBindings.findChildViewById(rootView, id);
      if (pickAPain == null) {
        break missingId;
      }

      id = R.id.seekBarHowStrongIsThePain;
      SeekBar seekBarHowStrongIsThePain = ViewBindings.findChildViewById(rootView, id);
      if (seekBarHowStrongIsThePain == null) {
        break missingId;
      }

      id = R.id.selectPainSpinner;
      Spinner selectPainSpinner = ViewBindings.findChildViewById(rootView, id);
      if (selectPainSpinner == null) {
        break missingId;
      }

      id = R.id.textView6;
      TextView textView6 = ViewBindings.findChildViewById(rootView, id);
      if (textView6 == null) {
        break missingId;
      }

      id = R.id.textViewPainStrenght;
      TextView textViewPainStrenght = ViewBindings.findChildViewById(rootView, id);
      if (textViewPainStrenght == null) {
        break missingId;
      }

      return new NewPainLogBinding((CoordinatorLayout) rootView, buttonLogPainReady,
          constraintLayout, editTextDescription, pickAPain, seekBarHowStrongIsThePain,
          selectPainSpinner, textView6, textViewPainStrenght);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
