// Generated by view binder compiler. Do not edit!
package com.ericaskari.healthapplication;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

/**
 * Generated by view binder compiler.
 */
public final class ProfileEditBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final Button birthdatePickButton;

  @NonNull
  public final TextView birthdateValue;

  @NonNull
  public final Button discardButton;

  @NonNull
  public final EditText firstnameValue;

  @NonNull
  public final EditText heightValue;

  @NonNull
  public final EditText lastNameValue;

  @NonNull
  public final EditText longTermIllnessValue;

  @NonNull
  public final Button saveButton;

  @NonNull
  public final EditText weightValue;

  private ProfileEditBinding(@NonNull CoordinatorLayout rootView,
      @NonNull Button birthdatePickButton, @NonNull TextView birthdateValue,
      @NonNull Button discardButton, @NonNull EditText firstnameValue,
      @NonNull EditText heightValue, @NonNull EditText lastNameValue,
      @NonNull EditText longTermIllnessValue, @NonNull Button saveButton,
      @NonNull EditText weightValue) {
    this.rootView = rootView;
    this.birthdatePickButton = birthdatePickButton;
    this.birthdateValue = birthdateValue;
    this.discardButton = discardButton;
    this.firstnameValue = firstnameValue;
    this.heightValue = heightValue;
    this.lastNameValue = lastNameValue;
    this.longTermIllnessValue = longTermIllnessValue;
    this.saveButton = saveButton;
    this.weightValue = weightValue;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ProfileEditBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ProfileEditBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.profile_edit, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ProfileEditBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.birthdate_pick_button;
      Button birthdatePickButton = ViewBindings.findChildViewById(rootView, id);
      if (birthdatePickButton == null) {
        break missingId;
      }

      id = R.id.birthdate_value;
      TextView birthdateValue = ViewBindings.findChildViewById(rootView, id);
      if (birthdateValue == null) {
        break missingId;
      }

      id = R.id.discard_button;
      Button discardButton = ViewBindings.findChildViewById(rootView, id);
      if (discardButton == null) {
        break missingId;
      }

      id = R.id.firstname_value;
      EditText firstnameValue = ViewBindings.findChildViewById(rootView, id);
      if (firstnameValue == null) {
        break missingId;
      }

      id = R.id.height_value;
      EditText heightValue = ViewBindings.findChildViewById(rootView, id);
      if (heightValue == null) {
        break missingId;
      }

      id = R.id.lastName_value;
      EditText lastNameValue = ViewBindings.findChildViewById(rootView, id);
      if (lastNameValue == null) {
        break missingId;
      }

      id = R.id.long_term_illness_value;
      EditText longTermIllnessValue = ViewBindings.findChildViewById(rootView, id);
      if (longTermIllnessValue == null) {
        break missingId;
      }

      id = R.id.save_button;
      Button saveButton = ViewBindings.findChildViewById(rootView, id);
      if (saveButton == null) {
        break missingId;
      }

      id = R.id.weight_value;
      EditText weightValue = ViewBindings.findChildViewById(rootView, id);
      if (weightValue == null) {
        break missingId;
      }

      return new ProfileEditBinding((CoordinatorLayout) rootView, birthdatePickButton,
          birthdateValue, discardButton, firstnameValue, heightValue, lastNameValue,
          longTermIllnessValue, saveButton, weightValue);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
