// Generated by view binder compiler. Do not edit!
package com.ericaskari.healthapplication;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

/**
 * Generated by view binder compiler.
 */
public final class ProfileBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final TextView birthdateValue;

  @NonNull
  public final TextView firstnameValue;

  @NonNull
  public final TextView heightValue;

  @NonNull
  public final TextView lastNameValue;

  @NonNull
  public final TextView longTermIllnessValue;

  @NonNull
  public final TextView weightValue;

  private ProfileBinding(@NonNull CoordinatorLayout rootView, @NonNull TextView birthdateValue,
      @NonNull TextView firstnameValue, @NonNull TextView heightValue,
      @NonNull TextView lastNameValue, @NonNull TextView longTermIllnessValue,
      @NonNull TextView weightValue) {
    this.rootView = rootView;
    this.birthdateValue = birthdateValue;
    this.firstnameValue = firstnameValue;
    this.heightValue = heightValue;
    this.lastNameValue = lastNameValue;
    this.longTermIllnessValue = longTermIllnessValue;
    this.weightValue = weightValue;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ProfileBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ProfileBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.profile, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ProfileBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.birthdate_value;
      TextView birthdateValue = ViewBindings.findChildViewById(rootView, id);
      if (birthdateValue == null) {
        break missingId;
      }

      id = R.id.firstname_value;
      TextView firstnameValue = ViewBindings.findChildViewById(rootView, id);
      if (firstnameValue == null) {
        break missingId;
      }

      id = R.id.height_value;
      TextView heightValue = ViewBindings.findChildViewById(rootView, id);
      if (heightValue == null) {
        break missingId;
      }

      id = R.id.lastName_value;
      TextView lastNameValue = ViewBindings.findChildViewById(rootView, id);
      if (lastNameValue == null) {
        break missingId;
      }

      id = R.id.long_term_illness_value;
      TextView longTermIllnessValue = ViewBindings.findChildViewById(rootView, id);
      if (longTermIllnessValue == null) {
        break missingId;
      }

      id = R.id.weight_value;
      TextView weightValue = ViewBindings.findChildViewById(rootView, id);
      if (weightValue == null) {
        break missingId;
      }

      return new ProfileBinding((CoordinatorLayout) rootView, birthdateValue, firstnameValue,
          heightValue, lastNameValue, longTermIllnessValue, weightValue);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
